captainVersion: 4
services:
    $$cap_appname:
        image: stilleshan/v2-ui
        restart: always
        volumes:
            - $$cap_appname-data:/etc/v2-ui
        caproverExtra:
            containerHttpPort: '65432'
caproverOneClickApp:
    variables: []
    instructions:
        start: V2-ui is a v2ray panel.
        end: V2-ui is deployed and available as $$cap_appname
    displayName: v2-ui
    description: Support multi-protocol multi-user v2ray panel.
